name: Deploy to Server

# Trigger deployment on push to main branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy files to server using SCP
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}       # Server IP
          username: ${{ secrets.SERVER_USER }}   # SSH user
          key: ${{ secrets.SERVER_SSH_KEY }}     # Private SSH key from GitHub Secrets
          source: "."                            # Deploy everything in repo root
          target: "/home/httppostlii/public_html/mvc"  # Target folder on server
          strip_components: 0                    # Keep folder structure

      # Step 3: Reload PM2 process
      - name: Reload PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pm2 reload MVC
